language: cpp

os:
  - linux
  #- osx

compiler:
  - gcc
  #- clang

#dist: trusty

env:
  global:
    - secure: "YVpSrf0YXyQKgz9Xd4VSN+K1szHNrlomWhm3h9RzbIJOs14lbBO5GW2oQaXWFfF8j77Ur36H9oyGT89OdHRAgCe/j5p8z313w1TfU3oj8/5dW6c7jVCmZ6chq2wiaIIHD61nzQ9poA5hkE3u4Jv3Ql/cfoAYZDd0hWu3jZBIA/wIjc9NI0zlHRrcMuJkhz+HLBzz5nUEBesRalrxX48PAN0cSZK2+TlwU2h7gIG5WsWwGzUckCF2j/EJTefeJ37B3C6EaEEa+uIQj3I4cqVV1SV9xp5B/6O1+lNfWzn+LpBVyulSxdW0ZF2Tn0V0H7prBeAHbMSqYFVnr//rRsulVBaOEDETyjlJee0Sx60n9V7FZdDDTn7hjKw6pyru7wwRkvjjV6P3nB4S+Bc1nEQuSRtcWbVnt1gza4fhiBJYQ/arVOWx3r8w5Om0R05OGveE8nulcmKosP3musfjW3ITscUahxFpeVojuk8p0p15lS7xlvcw6MEdxRxntopslJMjDZVwX+UvFZUzSozuFSGPRRJjwmFNV+D7hE+w23BqTk01e0JqAl7ZPG0ZwQ5Kt8LWtlbL1GqjNBHSpPTWnhg5RkNa6a9ez9x5RVNf87mmxHX6Y0W9ogVsXgH7xirLU4q2Zjr47vwkw7UWkcxfa4o3KXRAOAY8BnTFi9NMWWh4TJc="

addons:
  coverity_scan:
    project:
      name: "sasobadovinac/FreeCAD"
      description: "Build submitted via Travis CI"
    notification_email: saso.badovinac@gmail.com
    build_command: "make -j2"
    branch_pattern: coverity_scan
  apt:
    packages:
      - doxygen
      - libboost-dev
      - libboost-filesystem-dev
      - libboost-program-options-dev
      - libboost-python-dev
      - libboost-regex-dev
      - libboost-signals-dev
      - libboost-system-dev
      - libboost-thread-dev
      #- libcoin60
      - libcoin60-dev
      - libeigen3-dev
      - liboce-foundation-dev
      #- liboce-foundation1
      - liboce-modeling-dev
      #- liboce-modeling1
      - liboce-ocaf-dev
      #- liboce-ocaf-lite-dev
      #- liboce-ocaf-lite1
      #- liboce-ocaf1
      - liboce-visualization-dev
      #- liboce-visualization1
      - libopencascade-modeling-6.5.0
      - libpyside-dev
      - libqtcore4
      - libshiboken-dev
      - libxerces-c-dev
      #- libxmu-dev
      #- libxmu-headers
      #- libxmu6
      - libxmuu-dev
      #- libxmuu1
      - oce-draw
      - pyside-tools
      #- python-dev
      #- python-pyside
      - qt4-dev-tools
      #- qt4-qmake
      - shiboken
      - swig

#before_install:
#Patch the system - there is a bug related to invalid location of libs on ubuntu 12.04
    #- sudo ln -s /usr/lib/x86_64-linux-gnu/ /usr/lib/i386-linux-gnu

install:
    - mkdir build && cd build && cmake ../

#before_script:

script:
    - if [[ $CC == gcc ]]; then export NPROC=3; else export NPROC=1; fi
    - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then make -j$NPROC; fi
    - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then PYTHONPATH=$(pwd)/lib/ python -c "import sys, unittest, FreeCAD, TestApp; sys.exit(0 if unittest.TextTestRunner().run(TestApp.All()).wasSuccessful() else 1)"; fi

#after_success:

#after_failure:

#after_script:

notifications:
  email: false
