language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

#trusty
sudo: required
dist: trusty

before_install:
  #linux
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -qq; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y doxygen; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y libboost1.55-dev; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y libboost-filesystem1.55-dev; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y libboost-program-options1.55-dev; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y libboost-python1.55-dev; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y libboost-regex1.55-dev; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y libboost-signals1.55-dev; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y libboost-system1.55-dev; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y libboost-thread1.55-dev; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y libcoin80-dev; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y libeigen3-dev; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y liboce-foundation-dev; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y liboce-modeling-dev; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y liboce-ocaf-dev; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y liboce-visualization-dev; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y libpyside-dev; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y libqtcore4; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y libshiboken-dev; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y libxerces-c-dev; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y libxmuu-dev; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y oce-draw; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y pyside-tools; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y python-matplotlib; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y qt4-dev-tools; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y shiboken; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y swig; fi
  #travis trusty python-libpython version mismatch workaround
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo rm -rf /opt/python/2.7.10; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo rm -rf /opt/python/2.6.9; fi

  #osx
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew tap homebrew/science; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew tap sanelson/freecad; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install eigen freetype qt homebrew/science/oce python boost-python pyside pyside-tools xerces-c orocos-kdl; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install --without-framework --without-soqt sanelson/freecad/coin; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install --HEAD pivy; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then pip install matplotlib; fi

install:
  #linux
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then mkdir build && cd build && cmake ../; fi

  #osx
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then mkdir build && cd build && cmake -DFREECAD_USE_EXTERNAL_KDL=ON -DFREECAD_CREATE_MAC_APP=ON ../; fi

#before_script:

script:
  - make -j2
  #- PYTHONPATH=$(pwd)/lib/ python -c "import sys, unittest, FreeCAD, TestApp; sys.exit(0 if unittest.TextTestRunner().run(TestApp.All()).wasSuccessful() else 1)"
  - sudo make install
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then /usr/local/bin/FreeCAD --run-test 0; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then /usr/local/FreeCAD.app/Contents/bin/FreeCAD --run-test 0; fi

#after_success:

#after_failure:

#after_script:

notifications:
  email: false
  #irc:
    #channels:
      #- "irc.freenode.net#freecad"
    #template:
      #- "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"
    #on_success: always
    #on_failure: always
