language: cpp

os:
  #- linux
  - osx

compiler:
  - gcc
  - clang

#trusty
sudo: required
dist: trusty

before_install:
    - brew update
    - brew tap homebrew/science
    - brew tap sanelson/freecad
    - brew install eigen freetype qt homebrew/science/oce python boost-python pyside pyside-tools xerces-c orocos-kdl
    - brew install --without-framework --without-soqt sanelson/freecad/coin
    - brew install --HEAD pivy
    - pip install matplotlib

install:
    - mkdir build && cd build && cmake -DFREECAD_USE_EXTERNAL_KDL=ON -DFREECAD_CREATE_MAC_APP=ON ../

#before_script:

script:
    - make -j2
    #- PYTHONPATH=$(pwd)/lib/ python -c "import sys, unittest, FreeCAD, TestApp; sys.exit(0 if unittest.TextTestRunner().run(TestApp.All()).wasSuccessful() else 1)"
    - sudo make install/fast

#after_success:

#after_failure:

#after_script:

notifications:
  email: false
  #irc:
    #channels:
      #- "irc.freenode.net#freecad"
    #template:
      #- "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"
    #on_success: always
    #on_failure: always
