#version:

environment:
  matrix:
    - generator: "Visual Studio 12 Win64"
      ARCH: "Win64"
      Compiler: "MSVC2013"

#cache:

#configuration:

#branches:
#  only:

shallow_clone: true

# scripts that are called at very beginning, before repo cloning
#init:

#before_build:

# scripts that run after cloning repository
#install:

build_script:
  - cmd: CALL C:\projects\freecad\BuildAll.bat

#after_build:

#artifacts:

test: off  # to avoid discovering tests

#
# The following section automatically uploads artifacts
# whenever a tag is created on the master branch.
#
#deploy:
