#version:

image: Visual Studio 2015

environment:
  matrix:
    - generator: "Visual Studio 14 Win64"
      ARCH: "Win64"
      Compiler: "MSVC2015"
#    - generator: "Visual Studio 14"
#      ARCH: "Win32"
#      Compiler: "MSVC2015"

#cache: #

configuration:
  #- Debug
  - Release

#branches:
#  only:

clone_depth: 1600

# scripts that are called at very beginning, before repo cloning
#init:

#before_build:

# scripts that run after cloning repository
#todo cleanup libpacks on the FreeCAD-ports-cache repo
install:
  - cd C:\projects\freecad
  - appveyor DownloadFile https://dl.bintray.com/boostorg/release/1.67.0/source/boost_1_67_0.7z
  - if [%ARCH%] == [Win64] (appveyor DownloadFile https://github.com/apeltauer/FreeCAD/releases/download/LibPack_12.1/FreeCADLibs_12.1.2_x64_VC15.7z)
  - if [%ARCH%] == [Win64] (
      powershell -Command 7z x FreeCADLibs_12.1.2_x64_VC15.7z -oFreeCADLibs > nul &&
       7z x boost_1_67_0.7z -oFreeCADLibs > nul &&
       call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64 &&
       call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64 &&)
#      ren FreeCADLibs_12.1.2_x64_VC15_bin_release FreeCADLibs)
  - if [%ARCH%] == [Win32] (appveyor DownloadFile https://github.com/FreeCAD/FreeCAD-ports-cache/releases/download/v0.17/FreeCADLibs_11.5.1_x86_VC12.7z)
  - if [%ARCH%] == [Win32] (
      powershell -Command 7z x FreeCADLibs_11.5.1_x86_VC12.7z > nul &&
      ren FreeCADLibs_11.5_x86_VC12 FreeCADLibs)
  - dir

build_script:
  - cd C:\projects\freecad
  - mkdir build
  - cd build
  - cmake -DFREECAD_LIBPACK_DIR=C:\projects\freecad\FreeCADLibs
    -DBUILD_FEM_NETGEN=OFF
    -G "%generator%" ..
  - mkdir bin
  - xcopy C:\projects\freecad\FreeCADLibs\bin C:\projects\freecad\build\bin /E /Q
  - msbuild /m FreeCAD_Trunk.sln

#after_build:
  - cd C:\projects\freecad\build\bin\
  - FreeCADCmd.exe --run-test 0

#artifacts:

test: off  # to avoid discovering tests

#
# The following section automatically uploads artifacts
# whenever a tag is created on the master branch.
#
#deploy:
