#version:

environment:
  matrix:
    - generator: "Visual Studio 12 Win64"
      ARCH: "Win64"
      Compiler: "MSVC2013"

#cache:

configuration:
  #- Debug
  - Release

#branches:
#  only:

#shallow_clone: true

# scripts that are called at very beginning, before repo cloning
#init:

#before_build:

# scripts that run after cloning repository
install:
  - cd C:\projects\freecad
  - ps: Start-FileDownload https://github.com/sgrogan/FreeCAD/releases/download/0.17-med-test/FreeCADLibs_11.5_x64_VC12.7z
  - 7z x FreeCADLibs_11.5_x64_VC12.7z > nul
  - cmake --version
  #- ps: Start-FileDownload https://cmake.org/files/v3.5/cmake-3.5.1-win32-x86.zip
  #- 7z x cmake-3.5.1-win32-x86.zip > nul
  #- set PATH=C:\projects\freecad\cmake-3.5.1-win32-x86\bin;%PATH%
  #- cmake --version

build_script:
  - cd C:\projects\freecad
  - mkdir build
  - cd build
  - cmake -DFREECAD_LIBPACK_DIR=C:\projects\freecad\FreeCADLibs_11.5_x64_VC12
    -DBUILD_FEM_NETGEN
    -G "%generator%" ..
  - mkdir bin
  - xcopy C:\projects\freecad\FreeCADLibs_11.5_x64_VC12\bin C:\projects\freecad\build\bin /E /Q
  - echo %NUMBER_OF_PROCESSORS%
  - msbuild /m FreeCAD_Trunk.sln

#after_build:

#artifacts:

test: off  # to avoid discovering tests

#
# The following section automatically uploads artifacts
# whenever a tag is created on the master branch.
#
#deploy:
