#version:

environment:
  matrix:
    - generator: "Visual Studio 12 Win64"
      ARCH: "Win64"
      Compiler: "MSVC2013"

#cache:

#configuration:

#branches:
#  only:

shallow_clone: true

# scripts that are called at very beginning, before repo cloning
#init:

#before_build:

# scripts that run after cloning repository
install:
  - cmd: cd C:\projects\freecad
  - cmd: mkdir libpack
  - cmd: cd libpack
  - ps: Start-FileDownload https://github.com/FreeCAD/FreeCAD/releases/download/0.15/LibPack_11.1_x64_VC12.7z
  - 7z x LibPack_11.1_x64_VC12.7z > NUL

build_script:
  - cmd: cd C:\projects\freecad
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake -FREECAD_LIBPACK_DIR=C:\projects\freecad\libpack
    -FREECAD_USE_EXTERNAL_PIVY=ON
    -FREECAD_USE_FREETYPE=ON
    -G "%generator%" ..
  - cmd: xcopy C:\projects\freecad\libpack\bin C:\projects\freecad\build /E /Q
  - cmd: msbuild /m:4 FreeCAD_Trunk.sln

#after_build:

#artifacts:

test: off  # to avoid discovering tests

#
# The following section automatically uploads artifacts
# whenever a tag is created on the master branch.
#
#deploy:
