#version:

environment:
  matrix:
    - generator: "Visual Studio 12 Win64"
      ARCH: "Win64"
      #Compiler: "MSVC2013"
      CLCACHE_CL: "C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/x86_amd64/cl_original.exe"
    - generator: "Visual Studio 12"
      ARCH: "Win32"
      #Compiler: "MSVC2013"
      CLCACHE_CL: "C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/cl_original.exe"

cache:
  - C:\projects\clcache

configuration:
  #- Debug
  - Release

#branches:
#  only:

clone_depth: 1600

# scripts that are called at very beginning, before repo cloning
#init:

#before_build:

# scripts that run after cloning repository
install:
  - cd C:\projects\freecad
  - if [%ARCH%] == [Win64] (
      powershell -Command "Start-FileDownload https://github.com/FreeCAD/FreeCAD-ports-cache/releases/download/v0.17/FreeCADLibs_11.5.1_x64_VC12.7z" &&
      7z x FreeCADLibs_11.5.1_x64_VC12.7z > nul &&
      ren FreeCADLibs_11.5_x64_VC12 FreeCADLibs)
  - if [%ARCH%] == [Win32] (
      powershell -Command "Start-FileDownload https://github.com/FreeCAD/FreeCAD-ports-cache/releases/download/v0.17/FreeCADLibs_11.5.1_x86_VC12.7z" &&
      7z x FreeCADLibs_11.5.1_x86_VC12.7z > nul &&
      ren FreeCADLibs_11.5_x86_VC12 FreeCADLibs)
  #- ps: Start-FileDownload https://github.com/frerich/clcache/archive/v3.3.1.zip
  #- 7z x v3.3.1.zip > nul
  - ps: Start-FileDownload https://github.com/frerich/clcache/archive/f14d1a9f41e089db3839c2f9454920b3df4f2add.zip
  - 7z x f14d1a9f41e089db3839c2f9454920b3df4f2add.zip > nul
  - ren clcache-f14d1a9f41e089db3839c2f9454920b3df4f2add clcache-bin
  - python --version
  - set PATH=C:\\Python34;%PATH%
  - set PATH=C:\\Python34\\Scripts;%PATH%
  - python --version
  - cd clcache-bin
  #- pip install xxhash
  - pip install pyinstaller
  - pyinstaller --onefile clcache.py
  - cd server
  - python -m venv .
  - Scripts\pip install -r requirements.txt
  - ps: Start-Process C:\projects\freecad\clcache-bin\server\Scripts\python C:\projects\freecad\clcache-bin\server\clcachesrv.py
  - cd..
  #- clcachesrv.py
  #- pip install cx_Freeze==4.3.3
  #- cd C:\Python34\Scripts
  #- python.exe cxfreeze-postinstall
  #- cd C:\projects\freecad\clcache-bin
  ##- cxfreeze clcache.py --silent --target-dir dist
  - cd dist
  - dir
  - ren clcache.exe cl.exe
  - set CLCACHE_DIR=C:\projects\clcache
  - set CLCACHE_SERVER=1
  #- set CLCACHE_LOG=1
  #- set CLCACHE_HARDLINK=1
  #- set CLCACHE_NODIRECT=1
  - set CLCACHE_OBJECT_CACHE_TIMEOUT_MS=40000
  - if [%ARCH%] == [Win64] ( cd "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\x86_amd64" )
  - if [%ARCH%] == [Win32] ( cd "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin" )
  - ren cl.exe cl_original.exe
  - ren cl.exe.config cl_original.exe.config
  - if [%ARCH%] == [Win64] ( xcopy C:\projects\freecad\clcache-bin\dist\cl.exe "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\x86_amd64" )
  - if [%ARCH%] == [Win32] ( xcopy C:\projects\freecad\clcache-bin\dist\cl.exe "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin" )
  - cl.exe --help
  - cl.exe -M 2147483648
  - cl.exe -C
  - cl.exe -z
  - cl.exe -s

build_script:
  - cd C:\projects\freecad
  - mkdir build
  - cd build
  - cmake -D FREECAD_LIBPACK_DIR=C:\projects\freecad\FreeCADLibs
    -D BUILD_FEM_NETGEN=OFF
    -G "%generator%" ..
  - mkdir bin
  - xcopy C:\projects\freecad\FreeCADLibs\bin C:\projects\freecad\build\bin /E /Q
  - msbuild /m FreeCAD_Trunk.sln

after_build:
  - cd C:\projects\freecad\build\bin\
  - FreeCADCmd.exe --run-test 0
  - cd "C:\projects\freecad\clcache-bin\dist"
  - cl.exe -s
  - cl.exe -c

#artifacts:

test: off  # to avoid discovering tests

#
# The following section automatically uploads artifacts
# whenever a tag is created on the master branch.
#
#deploy:
